
workflows:
  ios-release:
    name: iOS Release
    max_build_duration: 60

    environment:
      flutter: stable
      xcode: latest
      cocoapods: default

    scripts:
      - name: Install dependencies
        script: flutter pub get

      - name: Build ipa
        script: flutter build ios --release --no-codesign

      - name: Code signing with Codemagic CLI
        script: |
          keychain initialize
          app-store-connect fetch-signing-files $APP_STORE_APP_IDENTITY --type IOS_APP_ADHOC --create
          keychain add-certificates
          keychain add-identities
          flutter build ios --release

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      email:
        recipients:
          - rishabh777ry@gmail.com

