name: attendance_taker
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  sqflite: ^2.2.8+4
  path: ^1.8.2
  csv:

dev_dependencies:
  flutter_test:
    sdk: flutter
  fluttertoast: ^8.2.2
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets: 
    - assets/images/
  fonts:
    - family: Gorgeous
      fonts:
        - asset: assets/font/Gorgeous.ttf
